export {
  buildAnnotationPageKey,
  normalizeAnnotationText,
  toAnnotationErrorResult,
  type AnnotationActionResult,
  type AnnotationAnchor,
  type AnnotationContainerFingerprint,
  type AnnotationLinkedElement,
  type AnnotationCreateThreadHandler,
  type AnnotationCreateThreadInput,
  type AnnotationCommitHistoryEntry,
  type AnnotationListThreadsHandler,
  type AnnotationListCommitHistoryHandler,
  type AnnotationListCommitHistoryInput,
  type AnnotationListThreadsInput,
  type AnnotationMessage,
  type AnnotationMoveThreadAnchorHandler,
  type AnnotationMoveThreadAnchorInput,
  type AnnotationPlugin,
  type AnnotationPluginContext,
  type AnnotationPoint,
  type AnnotationRect,
  type AnnotationReplyThreadHandler,
  type AnnotationReplyThreadInput,
  type AnnotationResultLink,
  type AnnotationDeleteThreadHandler,
  type AnnotationDeleteThreadInput,
  type AnnotationScrollChainNode,
  type AnnotationThread,
  type AnnotationThreadActionHandler,
  type AnnotationThreadActionInput,
  type AnnotationThreadStatus,
  type AnnotationTriggerKey,
  type AnnotationViewport,
} from "@deshlo/core/annotations";
