import type { OverlayProposedChange } from "@deshlo/core/overlay-plugin";

import { SourceInspectorError } from "./errors";
import { createGitHubProvider, type RepoProvider } from "./githubProvider";
import {
  resolveRepoConfigForCurrentHost,
  type HostConfigInput,
} from "./hostConfig";
import { applyTextReplacement } from "./jsxTextEdit";
import {
  createManagedPrState,
  parseManagedPrState,
  upsertManagedPrStateChange,
  writeManagedPrState,
  type ManagedPrState,
} from "./prState";
import { parseSourceLoc } from "./sourceLoc";
import type {
  BranchesSuccess,
  CreateDraftPrSuccess,
  ParsedSourceLoc,
  PreviewChangeSuccess,
  ProposedChangeInput,
} from "./types";

function normalizeRepoPath(value: string): string {
  return value
    .replace(/\\/g, "/")
    .replace(/^\/+/, "")
    .replace(/^\.\/+/, "");
}

function resolveGitHubFilePath(sourceFilePath: string, prefixOverride?: string): string {
  const normalizedSourcePath = normalizeRepoPath(sourceFilePath);
  const rawPrefix =
    prefixOverride?.trim() ||
    process.env.NEXT_PUBLIC_SOURCE_INSPECTOR_GITHUB_PATH_PREFIX?.trim() ||
    "";
  const normalizedPrefix = rawPrefix
    .replace(/\\/g, "/")
    .replace(/^\/+/, "")
    .replace(/\/+$/, "");

  if (!normalizedPrefix) {
    return normalizedSourcePath;
  }

  if (
    normalizedSourcePath === normalizedPrefix ||
    normalizedSourcePath.startsWith(`${normalizedPrefix}/`)
  ) {
    return normalizedSourcePath;
  }

  return `${normalizedPrefix}/${normalizedSourcePath}`;
}

function slugifyTag(tagName: string): string {
  return (
    tagName
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "") || "element"
  );
}

function generateBranchName(tagName: string, prefixOverride?: string): string {
  const prefix =
    prefixOverride?.trim() ||
    process.env.NEXT_PUBLIC_SOURCE_INSPECTOR_BRANCH_PREFIX ||
    "source-inspector";
  const timestamp = Date.now();
  const slug = slugifyTag(tagName);
  return `${prefix}/${slug}-${timestamp}`;
}

function assertValidInput(input: ProposedChangeInput): void {
  if (!input.tagName?.trim()) {
    throw new SourceInspectorError("INVALID_SOURCE_LOC", "tagName is required.");
  }

  if (!input.sourceLoc?.trim()) {
    throw new SourceInspectorError("INVALID_SOURCE_LOC", "sourceLoc is required.");
  }

  if (!input.baseBranch?.trim()) {
    throw new SourceInspectorError("BASE_BRANCH_NOT_FOUND", "baseBranch is required.");
  }

  if (!input.selectedText?.trim()) {
    throw new SourceInspectorError(
      "NON_TEXT_NODE",
      "Selected element does not contain direct text. Select a text element."
    );
  }

  if (!input.proposedText?.trim()) {
    throw new SourceInspectorError("NO_DIFF", "Proposed changes cannot be empty.");
  }
}

function assertValidBatchInput(inputs: ProposedChangeInput[]): void {
  if (inputs.length === 0) {
    throw new SourceInspectorError("NO_DIFF", "No staged changes were provided.");
  }

  const baseBranch = inputs[0]?.baseBranch;
  for (const input of inputs) {
    assertValidInput(input);
    if (input.baseBranch !== baseBranch) {
      throw new SourceInspectorError(
        "PROVIDER_ERROR",
        "Batch submit must target a single base branch."
      );
    }
  }
}

function dedupeInputsBySourceLoc(inputs: ProposedChangeInput[]): ProposedChangeInput[] {
  const deduped: ProposedChangeInput[] = [];
  for (const input of inputs) {
    const existingIndex = deduped.findIndex((entry) => entry.sourceLoc === input.sourceLoc);
    if (existingIndex >= 0) {
      deduped[existingIndex] = input;
      continue;
    }
    deduped.push(input);
  }
  return deduped;
}

function hasKnownCommitSha(commitSha?: string): commitSha is string {
  return Boolean(commitSha && commitSha.trim() && commitSha.trim() !== "unknown");
}

function resolveKnownBatchCommitSha(inputs: ProposedChangeInput[]): string | undefined {
  const knownCommitShas = Array.from(
    new Set(
      inputs
        .map((entry) => entry.commitSha?.trim() || "unknown")
        .filter((entry) => entry && entry !== "unknown")
    )
  );

  if (knownCommitShas.length > 1) {
    throw new SourceInspectorError(
      "PROVIDER_ERROR",
      "Staged changes contain mixed commit revisions. Submit one revision at a time."
    );
  }

  return knownCommitShas[0];
}

function toIsoNow(): string {
  return new Date().toISOString();
}

function buildPrBody(params: {
  sourceLoc: string;
  oldText: string;
  newText: string;
  baseBranch: string;
  commitSha?: string;
}): string {
  const lines = [
    "This draft PR was generated by Source Inspector.",
    "",
    `- Source location: \`${params.sourceLoc}\``,
    `- Base branch: \`${params.baseBranch}\``,
    `- Old text: \`${params.oldText}\``,
    `- New text: \`${params.newText}\``,
  ];

  if (params.commitSha && params.commitSha !== "unknown") {
    lines.push(`- Build commit: \`${params.commitSha}\``);
  }

  return lines.join("\n");
}

function buildBatchPrBody(params: {
  baseBranch: string;
  commitSha?: string;
  sourceLocs: string[];
}): string {
  const lines = [
    "This draft PR was generated by Source Inspector.",
    "",
    `- Base branch: \`${params.baseBranch}\``,
    `- Updated locations: ${params.sourceLocs.length}`,
  ];

  if (params.commitSha && params.commitSha !== "unknown") {
    lines.push(`- Build commit: \`${params.commitSha}\``);
  }

  if (params.sourceLocs.length > 0) {
    lines.push("", "Updated source locations:");
    for (const sourceLoc of params.sourceLocs) {
      lines.push(`- \`${sourceLoc}\``);
    }
  }

  return lines.join("\n");
}

export interface ClientRuntimeContext {
  token: string;
  runtime?: SourceInspectorRuntimeOptions;
}

export interface SourceInspectorRuntimeOptions {
  host?: string;
  hostConfig?: HostConfigInput;
  githubPathPrefix?: string;
  branchPrefix?: string;
}

interface ReplacementResult {
  preview: PreviewChangeSuccess;
  updatedSourceCode: string;
}

interface ReusableManagedPr {
  prNumber: number;
  prUrl: string;
  branchName: string;
  body: string;
  state: ManagedPrState;
}

interface BatchCandidateChange {
  input: ProposedChangeInput;
  parsedSourceLoc: ParsedSourceLoc;
  repoFilePath: string;
}

interface AppliedBatchChange {
  sourceLoc: string;
  tagName: string;
  selectedText: string;
  newText: string;
}

interface BatchReplacementResult {
  updatedFiles: Array<{ path: string; content: string }>;
  appliedChanges: AppliedBatchChange[];
}

function createProviderFromContext(context: ClientRuntimeContext): RepoProvider {
  const token = context.token.trim();
  if (!token) {
    throw new SourceInspectorError("AUTH_REQUIRED", "GitHub token is required.");
  }

  const repoConfig = resolveRepoConfigForCurrentHost(
    context.runtime?.host,
    context.runtime?.hostConfig
  );
  return createGitHubProvider(repoConfig, token);
}

async function resolveReplacement(params: {
  input: ProposedChangeInput;
  provider: RepoProvider;
  runtime?: SourceInspectorRuntimeOptions;
  ref: string;
  selectedText: string;
}): Promise<ReplacementResult> {
  const { input, provider, runtime, ref, selectedText } = params;
  const parsedSourceLoc = parseSourceLoc(input.sourceLoc);
  const repoFilePath = resolveGitHubFilePath(parsedSourceLoc.filePath, runtime?.githubPathPrefix);
  const file = await provider.getFileContent(repoFilePath, ref);

  const replacement = applyTextReplacement({
    sourceCode: file.content,
    sourceLoc: parsedSourceLoc,
    tagName: input.tagName,
    selectedText,
    proposedText: input.proposedText,
  });

  return {
    preview: {
      filePath: repoFilePath,
      oldText: replacement.oldText,
      newText: replacement.newText,
      line: parsedSourceLoc.line,
      column: parsedSourceLoc.column,
      tagName: input.tagName,
      branchNamePreview: generateBranchName(input.tagName, runtime?.branchPrefix),
    },
    updatedSourceCode: replacement.updatedSourceCode,
  };
}

async function buildPreview(
  input: ProposedChangeInput,
  provider: RepoProvider,
  runtime?: SourceInspectorRuntimeOptions
): Promise<ReplacementResult> {
  assertValidInput(input);
  await provider.getBranchHeadSha(input.baseBranch);

  return resolveReplacement({
    input,
    provider,
    runtime,
    ref: input.baseBranch,
    selectedText: input.selectedText,
  });
}

function findExistingChangeSelectedText(
  state: ManagedPrState,
  sourceLoc: string
): string | null {
  const existing = state.changes.find((change) => change.sourceLoc === sourceLoc);
  return existing ? existing.proposedText : null;
}

async function findReusableManagedPr(
  provider: RepoProvider,
  baseBranch: string,
  commitSha?: string
): Promise<ReusableManagedPr | null> {
  if (!hasKnownCommitSha(commitSha)) {
    return null;
  }

  const openPrs = await provider.listOpenPullRequests();
  for (const pr of openPrs) {
    if (!pr.draft || pr.baseBranch !== baseBranch) {
      continue;
    }

    const state = parseManagedPrState(pr.body);
    if (!state) {
      continue;
    }

    if (state.base.branch !== baseBranch || state.base.commitSha !== commitSha) {
      continue;
    }

    return {
      prNumber: pr.prNumber,
      prUrl: pr.prUrl,
      branchName: pr.headBranch,
      body: pr.body,
      state,
    };
  }

  return null;
}

function sortBatchChangesDescending(left: BatchCandidateChange, right: BatchCandidateChange): number {
  if (left.parsedSourceLoc.line !== right.parsedSourceLoc.line) {
    return right.parsedSourceLoc.line - left.parsedSourceLoc.line;
  }

  return right.parsedSourceLoc.column - left.parsedSourceLoc.column;
}

async function applyBatchReplacements(params: {
  provider: RepoProvider;
  runtime?: SourceInspectorRuntimeOptions;
  ref: string;
  inputs: ProposedChangeInput[];
  managedState?: ManagedPrState;
}): Promise<BatchReplacementResult> {
  const { provider, runtime, ref, inputs, managedState } = params;

  const candidates: BatchCandidateChange[] = inputs.map((input) => {
    const parsedSourceLoc = parseSourceLoc(input.sourceLoc);
    return {
      input,
      parsedSourceLoc,
      repoFilePath: resolveGitHubFilePath(parsedSourceLoc.filePath, runtime?.githubPathPrefix),
    };
  });

  const byFilePath = new Map<string, BatchCandidateChange[]>();
  for (const candidate of candidates) {
    const existing = byFilePath.get(candidate.repoFilePath) || [];
    existing.push(candidate);
    byFilePath.set(candidate.repoFilePath, existing);
  }

  const updatedFiles: Array<{ path: string; content: string }> = [];
  const appliedChanges: AppliedBatchChange[] = [];

  for (const [filePath, fileCandidates] of byFilePath.entries()) {
    const file = await provider.getFileContent(filePath, ref);
    let sourceCode = file.content;

    for (const candidate of fileCandidates.sort(sortBatchChangesDescending)) {
      const selectedText =
        managedState && findExistingChangeSelectedText(managedState, candidate.input.sourceLoc)
          ? findExistingChangeSelectedText(managedState, candidate.input.sourceLoc)!
          : candidate.input.selectedText;

      const replacement = applyTextReplacement({
        sourceCode,
        sourceLoc: candidate.parsedSourceLoc,
        tagName: candidate.input.tagName,
        selectedText,
        proposedText: candidate.input.proposedText,
      });

      sourceCode = replacement.updatedSourceCode;
      appliedChanges.push({
        sourceLoc: candidate.input.sourceLoc,
        tagName: candidate.input.tagName,
        selectedText: candidate.input.selectedText,
        newText: replacement.newText,
      });
    }

    updatedFiles.push({
      path: filePath,
      content: sourceCode,
    });
  }

  if (updatedFiles.length === 0 || appliedChanges.length === 0) {
    throw new SourceInspectorError("NO_DIFF", "No effective changes to submit.");
  }

  return {
    updatedFiles,
    appliedChanges,
  };
}

async function commitBatchFileChanges(params: {
  provider: RepoProvider;
  branchName: string;
  updatedFiles: Array<{ path: string; content: string }>;
  commitMessage: string;
}): Promise<string> {
  const { provider, branchName, updatedFiles, commitMessage } = params;
  const headCommitSha = await provider.getBranchHeadSha(branchName);
  const baseTreeSha = await provider.getCommitTreeSha(headCommitSha);
  const treeSha = await provider.createTree({
    baseTreeSha,
    files: updatedFiles,
  });
  const commitSha = await provider.createCommit({
    message: commitMessage,
    treeSha,
    parentCommitSha: headCommitSha,
  });
  await provider.updateBranchHead({
    branch: branchName,
    commitSha,
  });

  return commitSha;
}

export async function getBranches(context: ClientRuntimeContext): Promise<BranchesSuccess> {
  const repoConfig = resolveRepoConfigForCurrentHost(
    context.runtime?.host,
    context.runtime?.hostConfig
  );
  const provider = createGitHubProvider(repoConfig, context.token);

  const branches = await provider.listBranches();
  if (branches.length === 0) {
    throw new SourceInspectorError("BASE_BRANCH_NOT_FOUND", "Repository has no branches.");
  }

  const fallback = branches.includes("main") ? "main" : branches[0];

  return {
    branches,
    defaultBaseBranch: repoConfig.defaultBaseBranch || fallback,
  };
}

export async function previewProposedChangeWithProvider(
  input: ProposedChangeInput,
  provider: RepoProvider,
  runtime?: SourceInspectorRuntimeOptions
): Promise<PreviewChangeSuccess> {
  const { preview } = await buildPreview(input, provider, runtime);
  return preview;
}

export async function createDraftPrFromProposedChangesWithProvider(
  rawInputs: ProposedChangeInput[],
  provider: RepoProvider,
  runtime?: SourceInspectorRuntimeOptions
): Promise<CreateDraftPrSuccess> {
  const inputs = dedupeInputsBySourceLoc(rawInputs);
  assertValidBatchInput(inputs);

  const baseBranch = inputs[0].baseBranch;
  const baseSha = await provider.getBranchHeadSha(baseBranch);
  const knownCommitSha = resolveKnownBatchCommitSha(inputs);
  const reusableManagedPr = await findReusableManagedPr(provider, baseBranch, knownCommitSha);

  const branchName = reusableManagedPr
    ? reusableManagedPr.branchName
    : generateBranchName(inputs[0].tagName || "batch", runtime?.branchPrefix);
  const refForRead = reusableManagedPr ? reusableManagedPr.branchName : baseBranch;

  const batchReplacement = await applyBatchReplacements({
    provider,
    runtime,
    ref: refForRead,
    inputs,
    managedState: reusableManagedPr?.state,
  });

  if (!reusableManagedPr) {
    await provider.createBranch(branchName, baseSha);
  }

  const commitSha = await commitBatchFileChanges({
    provider,
    branchName,
    updatedFiles: batchReplacement.updatedFiles,
    commitMessage: `Source Inspector: apply ${batchReplacement.appliedChanges.length} text update(s)`,
  });

  const updatedAt = toIsoNow();

  if (reusableManagedPr) {
    let updatedState = reusableManagedPr.state;
    for (const change of batchReplacement.appliedChanges) {
      updatedState = upsertManagedPrStateChange(updatedState, {
        sourceLoc: change.sourceLoc,
        tagName: change.tagName,
        selectedText: change.selectedText,
        proposedText: change.newText,
        lastAppliedCommitSha: commitSha,
        updatedAt,
      });
    }

    const nextPrBody = writeManagedPrState(reusableManagedPr.body, updatedState);
    await provider.updatePullRequestBody(reusableManagedPr.prNumber, nextPrBody);

    return {
      action: "updated",
      branchName,
      commitSha,
      prNumber: reusableManagedPr.prNumber,
      prUrl: reusableManagedPr.prUrl,
      affectedCount: batchReplacement.appliedChanges.length,
    };
  }

  const first = batchReplacement.appliedChanges[0];
  let state = createManagedPrState(
    {
      branch: baseBranch,
      commitSha: knownCommitSha || "unknown",
    },
    {
      sourceLoc: first.sourceLoc,
      tagName: first.tagName,
      selectedText: first.selectedText,
      proposedText: first.newText,
      lastAppliedCommitSha: commitSha,
      updatedAt,
    }
  );

  for (const change of batchReplacement.appliedChanges.slice(1)) {
    state = upsertManagedPrStateChange(state, {
      sourceLoc: change.sourceLoc,
      tagName: change.tagName,
      selectedText: change.selectedText,
      proposedText: change.newText,
      lastAppliedCommitSha: commitSha,
      updatedAt,
    });
  }

  const prTitle = `Source Inspector: apply ${batchReplacement.appliedChanges.length} text update(s)`;
  const prBody = writeManagedPrState(
    buildBatchPrBody({
      baseBranch,
      commitSha: knownCommitSha,
      sourceLocs: batchReplacement.appliedChanges.map((change) => change.sourceLoc),
    }),
    state
  );

  const pr = await provider.createDraftPullRequest({
    title: prTitle,
    body: prBody,
    head: branchName,
    base: baseBranch,
  });

  return {
    action: "created",
    branchName,
    commitSha,
    prNumber: pr.prNumber,
    prUrl: pr.prUrl,
    affectedCount: batchReplacement.appliedChanges.length,
  };
}

export async function createDraftPrFromProposedChangeWithProvider(
  input: ProposedChangeInput,
  provider: RepoProvider,
  runtime?: SourceInspectorRuntimeOptions
): Promise<CreateDraftPrSuccess> {
  // Keep compatibility for single-submit callers by delegating to the batch flow.
  return createDraftPrFromProposedChangesWithProvider([input], provider, runtime);
}

export async function listProposedChangesWithProvider(
  provider: RepoProvider
): Promise<OverlayProposedChange[]> {
  const openPrs = await provider.listOpenPullRequests();
  const mapped: OverlayProposedChange[] = [];

  for (const pr of openPrs) {
    const state = parseManagedPrState(pr.body);
    if (!state) {
      continue;
    }

    for (const change of state.changes) {
      mapped.push({
        changeId: change.changeId,
        sourceLoc: change.sourceLoc,
        tagName: change.tagName,
        selectedText: change.selectedText,
        proposedText: change.proposedText,
        status: change.status,
        baseBranch: state.base.branch,
        baseCommitSha: state.base.commitSha,
        lastAppliedCommitSha: change.lastAppliedCommitSha,
        updatedAt: change.updatedAt,
        prNumber: pr.prNumber,
        prUrl: pr.prUrl,
      });
    }
  }

  return mapped.sort((left, right) => right.updatedAt.localeCompare(left.updatedAt));
}

export async function previewProposedChange(
  input: ProposedChangeInput,
  context: ClientRuntimeContext
): Promise<PreviewChangeSuccess> {
  const provider = createProviderFromContext(context);
  return previewProposedChangeWithProvider(input, provider, context.runtime);
}

export async function createDraftPrFromProposedChange(
  input: ProposedChangeInput,
  context: ClientRuntimeContext
): Promise<CreateDraftPrSuccess> {
  const provider = createProviderFromContext(context);
  return createDraftPrFromProposedChangeWithProvider(input, provider, context.runtime);
}

export async function createDraftPrFromProposedChanges(
  inputs: ProposedChangeInput[],
  context: ClientRuntimeContext
): Promise<CreateDraftPrSuccess> {
  const provider = createProviderFromContext(context);
  return createDraftPrFromProposedChangesWithProvider(inputs, provider, context.runtime);
}

export async function listProposedChanges(
  context: ClientRuntimeContext
): Promise<OverlayProposedChange[]> {
  const provider = createProviderFromContext(context);
  return listProposedChangesWithProvider(provider);
}
