export {
  type OverlayBatchSubmitHandler,
  type OverlayBatchSubmitInput,
  type OverlayBatchSubmitResult,
  buildOverlaySubmitInput,
  normalizeOverlayText,
  toOverlayErrorResult,
  type OverlayPlugin,
  type OverlayPluginContext,
  type OverlayProposedChange,
  type OverlayResultLink,
  type OverlayListProposedChangesHandler,
  type OverlaySelection,
  type OverlaySubmitHandler,
  type OverlaySubmitInput,
  type OverlaySubmitResult,
  type TriggerKey,
} from "@deshlo/core/overlay-plugin";
